[package]
name = "csrf"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-session = { version = "0.10.0", features = ["cookie-session"] }
actix-web = { version = "4.9.0", features = ["openssl"] }
openssl = "0.10.66"
rand = "0.8.5"
