[package]
name = "user_management"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
chrono = "0.4.38"
jsonwebtoken = "9.3.0"
rand = "0.8.5"
serde_json = "1.0.127"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.209", features = ["derive"] }