[package]
name = "user_management"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
chrono = "0.4.38"
jsonwebtoken = "9.3.0"
rocket = "0.5.1"
rocket_contrib = "0.4.11"
serde = "1.0.209"
serde_json = "1.0.127"
