[package]
name = "user-management"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
argon2 = "0.5.3"
diesel = {version="2.2.2", features=["sqlite", "chrono"] }
dotenvy = "0.15.7"
serde = {version="1.0.208", features=["derive"]}
